services:
  app:
    image: clear-solution-test-app
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user_manager_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=user_manager_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin